### ISSUE TITLE
Having a problem with get a Answer body

### ISSUE THREAD

**Issue by kyeongwook-ma** [lucjon/Py-StackExchange#31]
Thanks for these libraries,

But i have a problem with get a Answer's body

``` python
class Answer(JSONModel):
    """Describes an answer on a StackExchange site."""

    transfer = ('is_accepted', 'locked_date', 'question_id', 'up_vote_count', 'down_vote_count', 'view_count', 'score',
        'community_owned', 'title', 'body')
```

Here is the implementation of Answer class

As you can see the "transfer" statement, the code include "body" json object

But, "body" python class variable isn't exit

How to get a Answers body?

**Comment by MilesCranmer** [comment]
Thanks @lucjon. Is there any way I can pre-load the answers from a question ID? I think I may have figured out the filter for this, but I'm not sure if that functionality is available in this.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
As a side note, it seems it is impossible to load the body as markdown (body_markdown), even though it is possible to request it, and the __dict__ for the object shows that it was requested. Where should I look to solve this?

**Comment by lucjon** [comment]
Hello, apologies for the delayed response.

Both of the above are indeed possible: the main thing is to ensure that the filter you choose includes both the `question.answers` field and the `answer.body` and `question.body_markdown` fields (see e.g. [this demo](http://api.stackexchange.com/docs/questions-by-ids#order=desc&sort=activity&ids=4&filter=!-*f\(6rktpIY5&site=stackoverflow`) on the API page, with filter `!-*f(6rktpIY5`). Supplying this filter to the library, we get the following results:

    >>> import stackexchange
    >>> so = stackexchange.Site(stackexchange.StackOverflow)
    >>> q = so.question(4, filter = '!-*f(6rktpIY5')
    >>> q
    <Question 'While applying opacity to a form should we use a decimal or double value?' @ 7fcf39f9b198>
    >>> q.body_markdown
    'I want to use a track-bar to change a form&#39;s opacity.\r\n\r\nHere goes my code:\r\n\r\n    decimal trans = trackBar1.Value / 5000;\r\n    this.Opacity = trans;\r\n\r\nWhen I build the application, It gives following error:\r\n\r\n&gt; Cannot implicitly convert type &#39;decimal&#39; to &#39;double&#39;.\r\n\r\nI tried using `trans` a `double`, but then the control doesn&#39;t work. This code worked fine in past VB.NET project. \r\n\r\n'
    >>> q.answers[0].body
    "<p>An explicit cast to double isn't necessary.</p>\n\n<pre><code>double trans = (double)trackBar1.Value / 5000.0;\n</code></pre>\n\n<p>Identifying the constant as <code>5000.0</code> (or as <code>5000d</code>) is sufficient:</p>\n\n<pre><code>double trans = trackBar1.Value / 5000.0;\ndouble trans = trackBar1.Value / 5000d;\n</code></pre>\n"

The above is all performed with one request. If running the above code yourself does not give the expected results, try upgrading to the latest version of the library — if you still have any problems, don't hesitate to get back in touch.

**Comment by MilesCranmer** [comment]
Thanks, @lucjon, I will try it out! Here's the plugin I'm working on if you're curious: (made with your API): https://github.com/MilesCranmer/gso. There's no multi-answer support right now but I hope to add it soon after reading the demo you linked.

Cheers,
Miles

**Comment by lucjon** [comment]
That looks neat, I'll need to give it a go! I'm glad you found the library
useful.

2017-06-27 5:51 GMT+01:00 Miles Cranmer <notifications@github.com>:
