### ISSUE TITLE
search has no possibility return statistics

### ISSUE THREAD

**Issue by theroys** [lucjon/Py-StackExchange#36]
The search method does not have the possibility return statistics ..
so search with a filter total fails.. result always expects 'items'.. am i being wrong here..or we need to request for new function like seach_statistics

**Comment by lucjon** [comment]
The upstream API's default filter for the /search method does not return a `total` field on the wrapper, and so neither does Py-StackExchange by default. However, if you do request that the API use a filter which does include this field, then it will be exposed in the results returned by Py-StackExchange, e.g.:

    import stackexchange
    so = stackexchange.Site(stackexchange.StackOverflow)
    results = so.search(tagged = 'python', filter = '!9YdnSQVoS')
    print(results.total)

works as expected. As far as I am aware, the API does not support returning any other kinds of statistics in the results of a `/search` call.

Please let me know if this is what you were meaning, and if this answers your question.

**Comment by theroys** [comment]
Thanks for quick answer .. i was looking nearly for same..
I would like to have a query like following
https://api.stackexchange.com/2.2/questions?fromdate=1393632000&todate=1425168000&order=desc&sort=activity&intitle=angularjs&site=stackoverflow&filter=total

So i tried with simple code as following 

total being one of the default filter, i tried following
------------------------------
import stackexchange
so = stackexchange.Site(stackexchange.StackOverflow)
results = so.search(intitle = 'python', filter = 'total')
print(results.total)
-----------------------------

However it seems it fails at core.py in stackexchage api  nornal_to_resultset method keyerror 'items'...

As far as i can see , it has to do with below code snippet, am i making mistaking 

------------
@staticmethod
    def normal_to_resultset(site, json, typ, collection):
        # the parameter 'collection' may be need in future, and was needed pre-2.0
        return tuple([typ(x, site) for x in json['items']])

    @classmethod
    def json_to_resultset(cls, site, json, typ, collection, params=None):
        if 'has_more' in json:
            # we have a paginated resultset
            return cls.paginated_to_resultset(site, json, typ, collection, params)
        else:
            # this isn't paginated (unlikely but possible - eg badges)
            return cls.normal_to_resultset(site, json, typ, collection)
-----------------------------------------------------------
cheers

**Comment by lucjon** [comment]
Hi,

Sorry, you're absolutely right - I misunderstood the first time round. This should be fixed in the latest revision. Thanks again for making me aware of it.

**Comment by theroys** [comment]
:) great .. it works  :+1:
