### ISSUE TITLE
Enabling Throttling Controls Causes "IOError: [Errno 22] Invalid argument"

### ISSUE THREAD

**Issue by davidhwayne** [lucjon/Py-StackExchange#42]
This is probably due to an error in the code. In 106 in web.py which is currently 
```
halt(5 - (WebRequestManager.window - now).seconds)
```
The input `(WebRequestManager.window - now).seconds` is almost certainly negative (and much greater than 5) causing the error further downstream in when input into `time.sleep`. Suggested fix is to correct the order of the subtraction and replace the line with:
```
halt(5 - (now-WebRequestManager.window).seconds)
```

**Comment by lucjon** [comment]
Thanks very much for spotting this, I've made the change you suggested and the backing off in these circumstances is indeed working for me now. Let me know if the fix works for you.

**Comment by davidhwayne** [comment]
Glad I could be of some help. This does fix the error, thank you.
