### ISSUE TITLE
User Notifications?

### ISSUE THREAD

**Issue by jacobm001** [lucjon/Py-StackExchange#43]
Is it possible to use this library to get notifications for a specific user (me)? I noticed there's a StackAuth() object in one of the examples, but I don't see any documentation about it, or what it does.

**Comment by lucjon** [comment]
Unfortunately, at the moment, the library does not support any of the API endpoints which require user (OAuth) authentication, such as `/users/{id}/notifications` etc., which you would need to access notifications.
