### ISSUE TITLE
ImportError: No module named 'answer'

### ISSUE THREAD

**Issue by benyamin-noori** [lucjon/Py-StackExchange#58]
I installed the latest version using pip (version 0.5.0). When I try to import the library I get this error: 
    ImportError: No module named 'answer'
![image](https://user-images.githubusercontent.com/3122298/27559295-477c11a6-5a7d-11e7-8bfc-af32be4a5958.png)

**Comment by lucjon** [comment]
Hi,

Thanks for getting in touch. I'm afraid the PyPI package called `stackexchange` is in fact [an unrelated project](https://github.com/sourcepirate/stackexchange); you are probably best leaving an issue there, as I am not sure what is causing the problem you are having.

If you would like to use this project, it is in PyPI under the package name `py-stackexchange` — please leave another issue if there are any other problems :)
