### ISSUE TITLE
Missing 'closed_date' attribute for question

### ISSUE THREAD

**Issue by vkotovv** [lucjon/Py-StackExchange#63]
According to https://api.stackexchange.com/docs/types/question, `Question` object has an attribute called `closed_date`.   
But there is no such attribute in the [Question model](https://github.com/lucjon/Py-StackExchange/blob/master/stackexchange/models.py#L196).

**Comment by lucjon** [comment]
Thanks for spotting this, that should be fixed in `master` now. Let me know if you notice anything else missing!

**Comment by vkotovv** [comment]
This was fixed in https://github.com/lucjon/Py-StackExchange/commit/ecb753d68103fefb87dfde2bbfd14ae7bac45b35, closing
